version: '3'

services:
  sqlite:
    build: .
    container_name: sqlite_container
    volumes:
      - ./db:/data/db
    stdin_open: true
    tty: true

  sql-explorer:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
    environment:
      - TZ=UTC
    volumes:
      - ./db:/data
    container_name: sql_explorer
