version: '3'

services:
  sqlite:
    build: .
    container_name: sqlite_container
    volumes:
      - proyecto:/data
    stdin_open: true
    tty: true

  sql-explorer:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - proyecto:/data

    container_name: sql_explorer
volumes:
  proyecto:
    name: database
