--TABLAS
drop table if exists usuarios;
create table usuarios (
    id_usuarios             number generated by default on null as identity,
    email                   varchar2(30),
    telefono                varchar2(9),
    nombre_apellidos        varchar2(50),
    contrasena              varchar2(16),
    direccion               varchar2(50),
    constraint pk_usuarios primary key(id_usuarios)
);

drop table if exists clientes;
create table clientes (
    id_clientes                 number generated by default on null as identity,
    email_cliente               varchar2(30),
    telefono_cliente            varchar2(9),
    nombre_apellidos_cliente    varchar2(50),
    contrasena_cliente          varchar2(16),
    direccion_cliente           varchar2(50),
    constraint pk_clientes primary key(id_clientes)
);

drop table if exists alojamientos;
create table alojamientos (
    id_alojamiento          number generated by default on null as identity,
    nom_alojamiento         varchar2(20),
    direccion_alojamiento   varchar2(50),
    num_huespedes           number(10),
    tipo_alojamiento        varchar2(20),
    constraint pk_alojamientos primary key(id_alojamiento)
);

drop table if exists reserva;
create table reserva (
    id_reserva          number generated by default on null as identity,
    fecha_ini           date,
    fecha_fin           date,
    id_cliente          number,
    id_alojamiento     varchar2(10),
    constraint pk_reserva primary key(id_reserva),
    constraint fk1 foreign key(id_cliente) references clientes(id_clientes),
    constraint fk3 foreign key(id_alojamiento) references alojamientos(id_alojamiento)
);

create table hoteles (
    id_alojamiento             number,
    numero_huespedes_hoteles    number(10),
    tipo_habitacion             varchar2(10),
    clasificacion               number(1),
    constraint pk_hoteles primary key(id_alojamiento),
    constraint fk4 foreign key(id_alojamiento) references alojamientos(id_alojamiento)
);

create table aps_turisticos (
    id_alojamiento     number,
    dist_al_centro_km   number(5),
    constraint pk_aps_turisticos primary key(id_alojamiento),
    constraint fk5 foreign key(id_alojamiento) references alojamientos(id_alojamiento)
);

--TRIGGER
CREATE OR REPLACE TRIGGER crear_alojamientos
AFTER INSERT ON alojamientos
FOR EACH ROW
BEGIN
    CASE
        WHEN :NEW.tipo_alojamiento = 'HOTEL' THEN
            INSERT INTO hoteles (id_alojamiento, numero_huespedes_hoteles, tipo_habitacion, clasificacion)
            VALUES (:NEW.id_alojamiento, DEFAULT, DEFAULT, DEFAULT);
        WHEN :NEW.tipo_alojamiento = 'APARTAMENTOS_TURISTICOS' THEN
            INSERT INTO aps_turisticos (id_alojamiento, dist_al_centro_km)
            VALUES (:NEW.id_alojamiento, DEFAULT);
    END CASE;
END;
/

/*INSERCION DATOS*/
    --usuarios
INSERT INTO usuarios (email, telefono, nombre_apellidos, contrasena, direccion)
VALUES ('usuario1@gmail.com', '123456789', 'Juan Pérez', '1234', 'Calle Falsa 123'),
       ('usuario2@gmail.com', '987654321', 'María García', '5678', 'Avenida Principal 456');

    --clientes
INSERT INTO clientes (email_cliente, telefono_cliente, nombre_apellidos_cliente, contrasena_cliente, direccion_cliente) 
VALUES ('cliente1@example.com', '123456789', 'John Doe', 'password1', '123 Main St'),
       ('cliente2@example.com', '987654321', 'Jane Smith', 'password2', '456 Elm St'),
       ('cliente3@example.com', '111222333', 'Michael Johnson', 'password3', '789 Oak St'),
       ('cliente4@example.com', '444555666', 'Emily Davis', 'password4', '234 Pine St'),
       ('cliente5@example.com', '777888999', 'Jessica Wilson', 'password5', '567 Maple St'),
       ('cliente6@example.com', '333222111', 'Daniel Martinez', 'password6', '890 Cedar St'),
       ('cliente7@example.com', '666555444', 'Samantha Brown', 'password7', '901 Birch St'),
       ('cliente8@example.com', '999888777', 'Matthew Taylor', 'password8', '345 Walnut St'),
       ('cliente9@example.com', '222333444', 'Amanda Anderson', 'password9', '678 Ash St'),
       ('cliente10@example.com', '555444333', 'Andrew Thomas', 'password10', '123 Spruce St');

    --alojamientos
INSERT INTO alojamientos (nom_alojamiento, direccion_alojamiento, num_huespedes, tipo_alojamiento)
VALUES ('Hotel Ejemplo', 'Calle Principal 123', 50, 'HOTEL'),
       ('Cabaña de Montaña', 'Camino del Bosque 45', 4, 'HOTEL'),
       ('Apartamento Costero', 'Paseo Marítimo 67', 6, 'APARTAMENTOS_TURISTICOS'),
       ('Villa del Lago', 'Avenida del Lago 89', 8, 'HOTEL'),
       ('Hostal La Plaza', 'Plaza Mayor 12', 20, 'HOTEL'),
       ('Albergue del Bosque', 'Sendero Verde s/n', 30, 'HOTEL'),
       ('Resort Paradise', 'Carretera del Paraíso km 10', 200, 'HOTEL'),
       ('Pensión del Sol', 'Calle del Sol 34', 15, 'HOTEL'),
       ('Casa Rural El Encanto', 'Camino Viejo 56', 10, 'HOTEL'),
       ('Apartahotel Playa Azul', 'Avenida de la Playa 78', 40, 'APARTAMENTOS_TURISTICOS');
    
    --reserva
INSERT INTO reserva (fecha_ini, fecha_fin, id_cliente, id_alojamiento)
VALUES ('2024-04-01', '2024-04-10', 1, 1),
       ('2024-04-05', '2024-04-15', 2, 2),
       ('2024-04-10', '2024-04-20', 3, 3),
       ('2024-04-15', '2024-04-25', 4, 4),
       ('2024-04-20', '2024-04-30', 5, 5),
       ('2024-04-25', '2024-05-05', 6, 6),
       ('2024-05-01', '2024-05-10', 7, 7),
       ('2024-05-05', '2024-05-15', 8, 8),
       ('2024-05-10', '2024-05-20', 9, 9),
       ('2024-05-15', '2024-05-20', 10, 10);